/* tslint:disable */
/* eslint-disable */
/**
 * Channel Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ChannelmanagerMarketResponseWithAssociations
 */
export interface ChannelmanagerMarketResponseWithAssociations {
    /**
     * 
     * @type {string}
     * @memberof ChannelmanagerMarketResponseWithAssociations
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelmanagerMarketResponseWithAssociations
     */
    'grn'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelmanagerMarketResponseWithAssociations
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelmanagerMarketResponseWithAssociations
     */
    'description'?: string;
    /**
     * 
     * @type {Array<ChannelmanagerCountryCode>}
     * @memberof ChannelmanagerMarketResponseWithAssociations
     */
    'countries'?: Array<ChannelmanagerCountryCode>;
    /**
     * 
     * @type {Array<ChannelmanagerMarketResponseWithAssociationsAssociation>}
     * @memberof ChannelmanagerMarketResponseWithAssociations
     */
    'associations'?: Array<ChannelmanagerMarketResponseWithAssociationsAssociation>;
    /**
     * 
     * @type {Date}
     * @memberof ChannelmanagerMarketResponseWithAssociations
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ChannelmanagerMarketResponseWithAssociations
     */
    'updatedAt'?: Date;
}
