/* tslint:disable */
/* eslint-disable */
/**
 * Channel Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ChannelmanagerChannelStatus = {
    Unknown: 'CH_STATUS_UNKNOWN',
    Active: 'CH_STATUS_ACTIVE',
    Disabled: 'CH_STATUS_DISABLED',
    UnderMaintenance: 'CH_STATUS_UNDER_MAINTENANCE'
} as const;
export type ChannelmanagerChannelStatus = typeof ChannelmanagerChannelStatus[keyof typeof ChannelmanagerChannelStatus];


export function ChannelmanagerChannelStatusFromJSON(json: any): ChannelmanagerChannelStatus {
    return ChannelmanagerChannelStatusFromJSONTyped(json, false);
}

export function ChannelmanagerChannelStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelmanagerChannelStatus {
    return json as ChannelmanagerChannelStatus;
}

export function ChannelmanagerChannelStatusToJSON(value?: ChannelmanagerChannelStatus | null): any {
    return value as any;
}

