/* tslint:disable */
/* eslint-disable */
/**
 * Channel Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ChannelmanagerChannelSettings
 */
export interface ChannelmanagerChannelSettings {
    /**
     * 
     * @type {boolean}
     * @memberof ChannelmanagerChannelSettings
     */
    'hideOosProducts'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelmanagerChannelSettings
     */
    'hidePricelessProducts'?: boolean;
}
