/* tslint:disable */
/* eslint-disable */
/**
 * Channel Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ChannelmanagerUpdateMarketRequest
 */
export interface ChannelmanagerUpdateMarketRequest {
    /**
     * 
     * @type {string}
     * @memberof ChannelmanagerUpdateMarketRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelmanagerUpdateMarketRequest
     */
    'id'?: string;
    /**
     * 
     * @type {ChannelmanagerUpdateMarketRequestPayload}
     * @memberof ChannelmanagerUpdateMarketRequest
     */
    'payload'?: ChannelmanagerUpdateMarketRequestPayload;
    /**
     * 
     * @type {Array<string>}
     * @memberof ChannelmanagerUpdateMarketRequest
     */
    'payloadMask'?: Array<string>;
}
