/**
 * Channel Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChannelmanagerChannelSettings } from '../models/ChannelmanagerChannelSettings';
import { ChannelmanagerChannelStatus } from '../models/ChannelmanagerChannelStatus';
import { ChannelmanagerChannelTypeWebsite } from '../models/ChannelmanagerChannelTypeWebsite';
import { ChannelmanagerLanguageCode } from '../models/ChannelmanagerLanguageCode';
import { HttpFile } from '../http/http';

export class ChannelmanagerUpdateChannelRequestPayload {
    'image'?: string;
    'name'?: string;
    'defaultLanguage'?: ChannelmanagerLanguageCode;
    'settings'?: ChannelmanagerChannelSettings;
    'website'?: ChannelmanagerChannelTypeWebsite;
    'status'?: ChannelmanagerChannelStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "image",
            "baseName": "image",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaultLanguage",
            "baseName": "defaultLanguage",
            "type": "ChannelmanagerLanguageCode",
            "format": ""
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "ChannelmanagerChannelSettings",
            "format": ""
        },
        {
            "name": "website",
            "baseName": "website",
            "type": "ChannelmanagerChannelTypeWebsite",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ChannelmanagerChannelStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChannelmanagerUpdateChannelRequestPayload.attributeTypeMap;
    }

    public constructor() {
    }
}



