/**
 * Channel Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum ChannelmanagerChannelStatus {
    Unknown = 'CH_STATUS_UNKNOWN',
    Active = 'CH_STATUS_ACTIVE',
    Disabled = 'CH_STATUS_DISABLED',
    UnderMaintenance = 'CH_STATUS_UNDER_MAINTENANCE'
}
