/**
 * Channel Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChannelmanagerChannelResponse } from '../models/ChannelmanagerChannelResponse';
import { HttpFile } from '../http/http';

export class ChannelmanagerMarketResponseWithAssociationsAssociation {
    'channel'?: ChannelmanagerChannelResponse;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "ChannelmanagerChannelResponse",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChannelmanagerMarketResponseWithAssociationsAssociation.attributeTypeMap;
    }

    public constructor() {
    }
}

