/**
 * Channel Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChannelmanagerMarketResponseWithAssociations } from '../models/ChannelmanagerMarketResponseWithAssociations';
import { HttpFile } from '../http/http';

export class ChannelmanagerListMarketsWithAssociationsResponse {
    'markets'?: Array<ChannelmanagerMarketResponseWithAssociations>;
    'nextPageToken'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "markets",
            "baseName": "markets",
            "type": "Array<ChannelmanagerMarketResponseWithAssociations>",
            "format": ""
        },
        {
            "name": "nextPageToken",
            "baseName": "nextPageToken",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChannelmanagerListMarketsWithAssociationsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

