/**
 * Channel Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChannelmanagerMarketResponse } from '../models/ChannelmanagerMarketResponse';
import { HttpFile } from '../http/http';

export class ChannelmanagerChannelResponseWithAssociationsAssociation {
    'market'?: ChannelmanagerMarketResponse;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "market",
            "baseName": "market",
            "type": "ChannelmanagerMarketResponse",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChannelmanagerChannelResponseWithAssociationsAssociation.attributeTypeMap;
    }

    public constructor() {
    }
}

